#! /bin/bash

GITUSER=epw

mkdir "$1"
cd "$1"
git init
git-touch README
git-touch .gitignore
echo "*~" > .gitignore
git commit -a -m "First commit"
git remote add origin git@github.com:$GITUSER/"$1".git
git push -u origin master
