#! /usr/bin/env python

import random, sys

if len(sys.argv) > 1:
    f = open (sys.argv[1])
else:
    f = open ("/usr/share/dict/words")

words = f.read().split ("\n")

print words[random.randint (0, len (words))]
